import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="grid grid-cols-[200px_1fr]">
          <aside className=" bg-amber-100 p-10 ">
            <ul>
              <li className="p-2">
                <Link href="/roles">Roles</Link>
              </li>
              <li className="p-2">
                <Link href="/usuarios">Usuarios</Link>
              </li>
            </ul>
          </aside>
          <main className="">{children}</main>
        </div>
      </body>
    </html>
  );
}
